#!/bin/zsh
#########  opensource / Cheatsheet ##########

#todo checkout script's at /usr/share/*


## cups Printer/Drucker
http://localhost:631/

## Date Zeit
# date

## Calender Wetter
# cal

# apropos            ## Comandline input helper zb. 'apropos vpn'

# alias phone-scrcpy='scrcpy -s 'your-adb-devices-id' -m 2110 -b 20m'                    #android-screen
# alias tablets-scrcpy='scrcpy -s 'your-adb-devices-id' -m 2110 -b 20m'                    # android-screen
# alias scp-up='  scp -rv'	#-P22	#scp -P 1234 file user@remote.host:/remote/location/
# alias scp-down='scp -rv'     #-P22	#scp -P 1234 user@remote.host:/remote/location/file ./
# manuel alias  rsync-up='rsync -e'ssh   -p22' --force -Rravuz --delete-before' #pkglist user@remotesystem:/path/           --exclude
# manuel alias  rsync-down='rsync -e'ssh -p22' --force -Rravuz --delete-before' #pkglist user@remotesystem:/path/
# manuel alias  rsyncvm='rsync -e 'ssh -p22'  $HOME/VirtualBox\ VMs/ 172.20.10.6:$HOME/VirtualBox\ VMs/ -r --force -avz'

# alias .config-update='rsync -e'ssh -p 22' --force -Rravuz --delete-before --exclude gnupg --exclude VirtualBox --exclude Barrier --exclude syncthing --exclude BraveSoftware --exclude .ssh --exclude ownCloud --exclude .stversions --exclude .xsession-errors .config/'   ## 172.0.0.1:

# rclone
#alias owncloud-encrypt='rclone --attr-timeout 3s --vfs-cache-mode full --vfs-read-chunk-size 100M       mount owncloud-encrypt crypt: $HOME/owncloud crypt   --allow-non-empty'

# Exec='prime-run' cmatrix                nvidia prime-run for nvidia properietary driver

## System Information
#systemd-analyze blame  #*startup-speedinfo
#systemd-analyze        #*startup-loadtime

######################################################################################

#echo '                                       -@                                              '
#echo '                                      .##@                                             '
#echo '                                     .####@                                            '
#echo '                                     @#####@                                           '
#echo '                                   . *######@                                          '
#echo '                                  .##@o@#####@                                         '
#echo '                                 /############@                                        '
#echo '                                /##############@                                       '
#echo '                               @######@**%######@                                      '
#echo '                              @######`     %#####o                                     '
#echo '                             @######@       ######%                                    '
#echo '                           -@#######h       ######@.`                                  '
#echo '                          /#####h**``       `**%@####@                                 '
#echo '                         @H@*`                    `*%#@                                '
#echo '                        *`                            `*                               '
